import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Court from '#models/court'
export default class extends BaseSeeder {
  async run() {
    await Court.createMany([
      {id: 1, 
        name: 'Badminton Court 1',
        location: 'Downtown Sports Center',
        type: 'Badminton',
        price_per_hour: 250,
        status:'Available',
        opening_time: '08.00',
        closing_time: '22.00',
      },
      {id: 2, 
        name: 'Badminton Court 2',
        location: 'Downtown Sports Center',
        type: 'Badminton',
        price_per_hour: 250,
        status:'Not Available',
        opening_time: '09.00',
        closing_time: '22.00',
      },
      {
        id: 3,
        name: 'Badminton Court 3',
        location: 'Eastside Gym',
        type: 'Badminton',
        price_per_hour: 300,
        status:'Available',

        opening_time: '07.00',
        closing_time: '21.00',
      },
      {id: 4,
        name: 'Badminton Court 4',
        location: 'Eastside Gym',
        type: 'Badminton',
        price_per_hour: 300,
        status:'Not Available',
        opening_time: '07.00',
        closing_time: '21.00',
      },
      {id: 5,
        name: 'Badminton Court 5',
        location: 'Westside Arena',
        type: 'Badminton',
        price_per_hour: 350,
        status:'Available',
        opening_time: '06.00',
        closing_time: '20.00',
      },
      {id: 6,
        name: 'Tennis Court 1',
        location: 'Downtown Sports Center',
        type: 'Tennis',
        price_per_hour: 500,
        status:'Available',
        opening_time: '08.00',
        closing_time: '22.00',
      },
      {id: 7,
        name: 'Tennis Court 2',
        location: 'Downtown Sports Center',
        type: 'Tennis',
        price_per_hour: 500,
        status:'Not Available',
        opening_time: '08.00',
        closing_time: '22.00',
      },
      {
        id: 8,
        name: 'Tennis Court 3',
        location: 'Eastside Gym',
        type: 'Tennis',
        price_per_hour: 600,
        status:'Available',
        opening_time: '07.00',
        closing_time: '21.00',
      },
      { id: 9,
        name: 'Tennis Court 4',
        location: 'Eastside Gym',
        type: 'Tennis',
        price_per_hour: 600,
        status:'Available',
        opening_time: '07.30',
        closing_time: '21.30',
      },
      { id: 10,
        name: 'Tennis Court 5',
        location: 'Westside Arena',
        type: 'Tennis',
        price_per_hour: 700,
        status:'Available',
        opening_time: '06.00',
        closing_time: '20.00',
      }
    ])
    }
}